#!/usr/bin/env python2
##!/astro/apps6/anaconda/bin/python2

from __future__ import print_function, division, absolute_import

import sys

#### Internal imports
from ProcessDAv import ProcessDAv
from Calcsfh import DefaultCalcsfh

# Invoke python scripts here after to process commands

def runProcessDav(path, commands):
    """Processes the fits from the custom flag -dAvrange=beg,end,step.

    Parameters
    ----------
    path : string
           Points to directory containing fits generated by -dAvrange.
    commands : list of strings
           Contains a list of the passed in commands from group_script.py.

    Returns
    -------
    out : None
    """
    print("Group run:", commands)
    # extract the baseName, global photometry and parameter file used the best dAv fits
    davFit = DefaultCalcsfh(commands[0])
    baseName = "_".join(davFit.fit.split("_")[:-2])
    photometry = davFit.phot
    param_file = davFit.parameter
    #ProcessDAv(path, baseName, photometry, param_file, bins=2)
    
    return None


def main():
    grouping = str(sys.argv[1])
    path = sys.argv[2]
    commands = sys.argv[3:]
    print("Commands:", commands)

    if grouping == 'bestdAv':
        runProcessDav(path, commands)

if __name__ == "__main__":
    main()
